default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: myth_busters_dev

test:
  <<: *default
  database: myth_busters_test

production:
  <<: *default
  database: myth_busters
